spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-properties: druid.stat.mergeSql=true
    url: jdbc:mysql://127.0.0.1:3306/security-web?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  http:
    encoding:
      charset: utf-8
logging:
  level:
    ## 打印请求及应答日志
    org.springframework.http.codec.json.Jackson2JsonDecoder: debug
    org.springframework.http.codec.json.Jackson2JsonEncoder: debug
##
pers:
  security:
    permit-url:
      - '/login'
      - '/captcha/image'
      - '/captcha/sms'
    captcha:
      image:
        ## 单位秒
        expire-time: 140
      sms:
        ## 单位秒
        expire-time: 150
      kaptcha-config:
        kaptcha.textproducer.char.length: 4
    jwt:
      ## 单位秒
      expire-time: 360
      sign-key: E10ADC3949BA59ABBE56E057F20F883E
      des-key: 12345678
